image:
  repository: "mysql"
  pullPolicy: IfNotPresent
  tag: "8"

replicaCount: 1

mysqlDatabase: devdb
mysqlUser: devuser
mysqlPassword: devpass
mysqlRootPassword: devroot

pvc:
  storage: 5Gi

service:
  type: ClusterIP
  port: 3306

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
