image:
  repository: "mysql"
  pullPolicy: IfNotPresent
  tag: "8"

replicaCount: 1 

service:
  type: ClusterIP
  port: 3306

mysqlDatabase: proddb
mysqlUser: produser
mysqlPassword: prodpass
mysqlRootPassword: prodroot
pvc:
  storage: 20Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
