image:
  repository: "mysql"
  pullPolicy: IfNotPresent
  tag: "8"

replicaCount: 1

service:
  type: ClusterIP
  port: 3306

mysqlDatabase: stagedb
mysqlUser: stageuser
mysqlPassword: stagepass
mysqlRootPassword: stageroot
pvc:
  storage: 10Gi
