image:
  repository: "mysql"
  pullPolicy: IfNotPresent
  tag: "8"

replicaCount: 1

service:
  type: ClusterIP
  port: 3306

mysqlDatabase: stagedb
mysqlUser: stageuser
mysqlPassword: stagepass
mysqlRootPassword: stageroot
pvc:
  storage: 10Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

storageClass:
  name: gp3-sc-mysql
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp3
    fsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
