apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/stackcouture/Java-WebAPP-CD.git
    targetRevision: main
    path: java-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: java-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true