apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            valuesFile: dev-values.yaml
            namespace: springboot-dev
          - env: stage
            valuesFile: stage-values.yaml
            namespace: springboot-stage
          - env: prod
            valuesFile: prod-values.yaml
            namespace: springboot-prod
  template:
    metadata:
      name: "springboot-{{env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: springboot-project
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      source:
        repoURL: https://github.com/stackcouture/Java-WebAPP-CD.git
        targetRevision: HEAD
        path: helm-charts/springboot
        helm:
          valueFiles:
            - "values/{{valuesFile}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
