apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stackcouture/Java-WebAPP-CD.git
    targetRevision: main
    helm:
      valueFiles:
        - deploy/dev-values.yaml

  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
