apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Source 1: Values repo
    - repoURL: https://github.com/stackcouture/Java-WebAPP-CD.git
      targetRevision: main
      ref: values

    # Source 2: Helm chart repo
    - repoURL: https://github.com/stackcouture/springboot-helm-chart.git
      targetRevision: main
      path: helm-charts/springboot
      helm:
        valueFiles:
          - $values/deploy/prod-values.yaml
