apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysqlRootPassword: {{ .Values.mysqlRootPassword }}
  mysqlUser: {{ .Values.mysqlUser }}
  mysqlPassword: {{ .Values.mysqlPassword }}
  mysqlDatabase: {{ .Values.mysqlDatabase }}
