replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: sha256:dee572e8b4e2f65f8a25286dc8c76739f5814763284bf02cd00597217ac77713

namespace: dev

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 8080
  name: java-dev-svc
  label: java-dev-app

ecr_credes_name: ecr-dev-creds

SPRING_DATASOURCE_URL: jdbc:mysql://mysql-dev:3306/devdb
SPRING_DATASOURCE_USERNAME: devuser
SPRING_DATASOURCE_PASSWORD: devpass
replicaCount: 2
pvc:
  storage: 5Gi
