replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: "8b07f0ad6c4acaa15dd1cde1ff7889bbe6dbda80"

namespace: java-ns

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 8080
  name: java-svc
  label: java-app

ecr_credes_name: ecr-creds