replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: "1350671a26f2b93b62e99e0156c882f829970556"

namespace: java-ns

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 8080
  name: java-svc
  label: java-app

ecr_credes_name: ecr-creds