replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
tag: 1ef9afef7f9d86dd1bab14c526e4b62f30f941ab

namespace: java-ns

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 8080
  name: java-svc
  label: java-app

ecr_credes_name: ecr-creds