apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:b917ca4a525f4fc8ed762629ee69154a7bb4bfdc
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
