apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:685ae8765e636d634b1027e1ef424469c0a1fc8a
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
