apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:13e84cf041f96c3b74372b3c35d1ae29a7993450
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
