apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:2e40d69b360fb9396e88af8a65aba830280b429d
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
