apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:b54b99ed3b27d62ea8cc9b9d52080bad0c3d25ab
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
