apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  namespace: java-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: 104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring:e274e7f9e7ea1b5e344e6406f574c965ae41567a
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-creds
