apiVersion: v1 
kind: Service
metadata: 
  name: java-svc 
  namespace: java-space 
spec: 
  type: NodePort
  selector: 
    app: java 
  ports: 
    - port: 8080
      protocol: TCP
      targetPort: 8080
