replicaCount: 3

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

namespace: node-ns
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  name: node-svc
  label: node-app
