replicaCount: 1

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: 8f2ae44e06c426573f780af3b6e7376f15c54f71-240

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

ecr_credes_name: ecr-dev-creds

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dev.stackcouture.online
      paths:
        - path: /
          pathType: Prefix
  tls: []

  
