replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: ca6073b70316ea363367b14a335cef6e86b82c16-228

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

ecr_credes_name: ecr-dev-creds

SPRING_DATASOURCE_URL: jdbc:mysql://mysql-dev-mysql.mysql-dev.svc.cluster.local:3306/devdb 
SPRING_DATASOURCE_USERNAME: devuser
SPRING_DATASOURCE_PASSWORD: devpass

pvc:
  storage: 5Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
