replicaCount: 1

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: ea44aa70edde42dcfaf22dfb38d0d6d0a3fb8b0c-233

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

ecr_credes_name: ecr-dev-creds

SPRING_DATASOURCE_URL: jdbc:mysql://mysql-dev-mysql.mysql-dev.svc.cluster.local:3306/devdb 
SPRING_DATASOURCE_USERNAME: devuser
SPRING_DATASOURCE_PASSWORD: devpass

pvc:
  storage: 5Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dev.myapp.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

  
