replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: fa35465bd0517b9ea0bf6956a64f2397df3d24c0-235

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80

ecr_credes_name: ecr-dev-creds

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dev.myapp.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

  
