replicaCount: 1
image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: f0e663778227b032cefc390f63e16a22e21846e3-249
imagePullSecrets: []
service:
  type: ClusterIP
  port: 80
ecr_credes_name: ecr-prod-creds
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: prod.stackcouture.online
      paths:
        - path: /
          pathType: Prefix
  tls: []
