replicaCount: 3

image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: "398d76a8eeb64dbf5d95c19a658618bbb09a11db-226"

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80

ecr_credes_name: ecr-prod-creds

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: stackcouture.online
      paths:
        - path: /
          pathType: Prefix
  tls: []