replicaCount: 1
image:
  repository: "104824081961.dkr.ecr.ap-south-1.amazonaws.com/javaspring"
  pullPolicy: IfNotPresent
  tag: "6335599ec86892546e923f6578fcd7bb7dd40f45"

namespace: stage

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

ecr_credes_name: ecr-stage-creds

SPRING_DATASOURCE_URL: jdbc:mysql://mysql-stage-mysql.mysql-stage.svc.cluster.local:3306/stagedb
SPRING_DATASOURCE_USERNAME: stageuser
SPRING_DATASOURCE_PASSWORD: stagepass

pvc:
  storage: 10Gi

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: stage.myapp.com
      paths:
        - path: /
          pathType: Prefix
  tls: []