apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.ecr_credes_name }}
      containers:
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /demo
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /demo
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          # env:
          #   - name: SPRING_DATASOURCE_URL
          #     value: {{ .Values.SPRING_DATASOURCE_URL | quote }}
          #   - name: SPRING_DATASOURCE_USERNAME
          #     value: {{ .Values.SPRING_DATASOURCE_USERNAME | quote }}
          #   - name: SPRING_DATASOURCE_PASSWORD
          #     value: {{ .Values.SPRING_DATASOURCE_PASSWORD | quote }}
            # - name: SPRING_DATASOURCE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Release.Name }}-springboot-secret
            #       key: SPRING_DATASOURCE_PASSWORD
      #     volumeMounts:
      #       - mountPath: /data
      #         name: springboot-pvc
      # volumes:
      #   - name: springboot-pvc
      #     persistentVolumeClaim:
      #       claimName: {{ .Release.Name }}-springboot-pvc
