name: Argo CD Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Argo CD CLI
        run: |
          curl -sSL https://github.com/argoproj/argo-cd/releases/download/v2.5.3/argocd-linux-amd64 -o /usr/local/bin/argocd
          chmod +x /usr/local/bin/argocd

      - name: Verify Argo CD token auth
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_API_TOKEN: ${{ secrets.ARGOCD_API_TOKEN }}
        run: |
          echo "Getting user info using token..."
          argocd account get-user-info \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_API_TOKEN \
            --insecure

      - name: Account list
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_API_TOKEN: ${{ secrets.ARGOCD_API_TOKEN }}
        run: |
          argocd account list \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_API_TOKEN \
            --insecure

      - name: Sync Argo CD Application
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_API_TOKEN: ${{ secrets.ARGOCD_API_TOKEN }}
        run: |
          echo "Syncing application: java-argo-application"
          argocd app sync java-argo-application \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_API_TOKEN \
            --insecure
