name: Promote Image Tag to Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Container image tag to promote"
        required: true
        type: string
      confirm:
        description: "Type 'yes' to confirm promotion"
        required: true
        type: string

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      
      FILE_PATH: helm-charts/springboot/values/prod-values.yaml
      IMAGE_PATH: .image.tag

    steps:
      - name: Confirm promotion intent
        run: |
          if [[ "${{ inputs.confirm }}" != "yes" ]]; then
            echo "Promotion not confirmed. You must type 'yes' to proceed."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Read current tag
        id: current
        run: |
          CURRENT_TAG=$(yq e "${IMAGE_PATH}" "${FILE_PATH}")
          echo "CURRENT_TAG=${CURRENT_TAG}" >> $GITHUB_ENV
          echo "Current tag: $CURRENT_TAG"

      - name: Check if tag already promoted
        if: env.CURRENT_TAG == inputs.image_tag
        run: |
          echo "The tag '${{ inputs.image_tag }}' is already in prod-values.yaml. No promotion needed."
          exit 0

      - name: Update stage-values.yaml with new tag
        run: |
          yq e "${IMAGE_PATH} = \"${{ inputs.image_tag }}\"" -i "${FILE_PATH}"

      - name: Commit and push changes to main
        run: |
          git config user.name "Naveen"
          git config user.email "naveenramlu28@gmail.com"
          git add "${FILE_PATH}"
          git commit -m "Promote image tag to ${{ inputs.image_tag }}"
          git push origin main
